/* XdmrtmXdmrtmProxy.h
   Generated by gSOAP 2.8.2 from Xdmrtm.h
   Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef XdmrtmXdmrtmProxy_H
#define XdmrtmXdmrtmProxy_H
#include "XdmrtmH.h"

namespace Xdmrtm {

class SOAP_CMAC XdmrtmProxy
{ public:
	struct soap *soap;
	bool own;
	/// Endpoint URL of service 'XdmrtmProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	XdmrtmProxy();
	/// Constructor to use/share an engine state
	XdmrtmProxy(struct soap*);
	/// Constructor with endpoint URL
	XdmrtmProxy(const char *url);
	/// Constructor with engine input+output mode control
	XdmrtmProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	XdmrtmProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	XdmrtmProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~XdmrtmProxy();
	/// Initializer used by constructors
	virtual	void XdmrtmProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'QueryRefStationType' (returns error code or SOAP_OK)
	virtual	int QueryRefStationType(_Xdmrtm__QueryRefStationType *Xdmrtm__QueryRefStationType, _Xdmrtm__QueryRefStationTypeResponse *Xdmrtm__QueryRefStationTypeResponse);

	/// Web service operation 'QueryRefDeviceType' (returns error code or SOAP_OK)
	virtual	int QueryRefDeviceType(_Xdmrtm__QueryRefDeviceType *Xdmrtm__QueryRefDeviceType, _Xdmrtm__QueryRefDeviceTypeResponse *Xdmrtm__QueryRefDeviceTypeResponse);

	/// Web service operation 'QueryRefDeviceProtocolType' (returns error code or SOAP_OK)
	virtual	int QueryRefDeviceProtocolType(_Xdmrtm__QueryRefDeviceProtocolType *Xdmrtm__QueryRefDeviceProtocolType, _Xdmrtm__QueryRefDeviceProtocolTypeResponse *Xdmrtm__QueryRefDeviceProtocolTypeResponse);

	/// Web service operation 'QueryRefDeviceModel' (returns error code or SOAP_OK)
	virtual	int QueryRefDeviceModel(_Xdmrtm__QueryRefDeviceModel *Xdmrtm__QueryRefDeviceModel, _Xdmrtm__QueryRefDeviceModelResponse *Xdmrtm__QueryRefDeviceModelResponse);

	/// Web service operation 'QueryRefDeviceFunc' (returns error code or SOAP_OK)
	virtual	int QueryRefDeviceFunc(_Xdmrtm__QueryRefDeviceFunc *Xdmrtm__QueryRefDeviceFunc, _Xdmrtm__QueryRefDeviceFuncResponse *Xdmrtm__QueryRefDeviceFuncResponse);

	/// Web service operation 'QueryRefDeviceModelFuncParam' (returns error code or SOAP_OK)
	virtual	int QueryRefDeviceModelFuncParam(_Xdmrtm__QueryRefDeviceModelFuncParam *Xdmrtm__QueryRefDeviceModelFuncParam, _Xdmrtm__QueryRefDeviceModelFuncParamResponse *Xdmrtm__QueryRefDeviceModelFuncParamResponse);

	/// Web service operation 'QueryMonOrganization' (returns error code or SOAP_OK)
	virtual	int QueryMonOrganization(_Xdmrtm__QueryMonOrganization *Xdmrtm__QueryMonOrganization, _Xdmrtm__QueryMonOrganizationResponse *Xdmrtm__QueryMonOrganizationResponse);

	/// Web service operation 'QueryMonControlCenter' (returns error code or SOAP_OK)
	virtual	int QueryMonControlCenter(_Xdmrtm__QueryMonControlCenter *Xdmrtm__QueryMonControlCenter, _Xdmrtm__QueryMonControlCenterResponse *Xdmrtm__QueryMonControlCenterResponse);

	/// Web service operation 'QueryStation' (returns error code or SOAP_OK)
	virtual	int QueryStation(_Xdmrtm__QueryStation *Xdmrtm__QueryStation, _Xdmrtm__QueryStationResponse *Xdmrtm__QueryStationResponse);

	/// Web service operation 'QueryDevice' (returns error code or SOAP_OK)
	virtual	int QueryDevice(_Xdmrtm__QueryDevice *Xdmrtm__QueryDevice, _Xdmrtm__QueryDeviceResponse *Xdmrtm__QueryDeviceResponse);

	/// Web service operation 'QueryRNC' (returns error code or SOAP_OK)
	virtual	int QueryRNC(_Xdmrtm__QueryRNC *Xdmrtm__QueryRNC, _Xdmrtm__QueryRNCResponse *Xdmrtm__QueryRNCResponse);

	/// Web service operation 'QueryAnt' (returns error code or SOAP_OK)
	virtual	int QueryAnt(_Xdmrtm__QueryAnt *Xdmrtm__QueryAnt, _Xdmrtm__QueryAntResponse *Xdmrtm__QueryAntResponse);

	/// Web service operation 'QueryDeviceFunc' (returns error code or SOAP_OK)
	virtual	int QueryDeviceFunc(_Xdmrtm__QueryDeviceFunc *Xdmrtm__QueryDeviceFunc, _Xdmrtm__QueryDeviceFuncResponse *Xdmrtm__QueryDeviceFuncResponse);

	/// Web service operation 'QueryDeviceFuncAnt' (returns error code or SOAP_OK)
	virtual	int QueryDeviceFuncAnt(_Xdmrtm__QueryDeviceFuncAnt *Xdmrtm__QueryDeviceFuncAnt, _Xdmrtm__QueryDeviceFuncAntResponse *Xdmrtm__QueryDeviceFuncAntResponse);

	/// Web service operation 'QueryUserLicenseStation' (returns error code or SOAP_OK)
	virtual	int QueryUserLicenseStation(_Xdmrtm__QueryUserLicenseStation *Xdmrtm__QueryUserLicenseStation, _Xdmrtm__QueryUserLicenseStationResponse *Xdmrtm__QueryUserLicenseStationResponse);

	/// Web service operation 'AllocLoadbalancingServer' (returns error code or SOAP_OK)
	virtual	int AllocLoadbalancingServer(_Xdmrtm__AllocLoadbalancingServer *Xdmrtm__AllocLoadbalancingServer, _Xdmrtm__AllocLoadbalancingServerResponse *Xdmrtm__AllocLoadbalancingServerResponse);

	/// Web service operation 'SubmitDeviceUsedLog' (returns error code or SOAP_OK)
	virtual	int SubmitDeviceUsedLog(_Xdmrtm__SubmitDeviceUsedLog *Xdmrtm__SubmitDeviceUsedLog, _Xdmrtm__SubmitDeviceUsedLogResponse *Xdmrtm__SubmitDeviceUsedLogResponse);

	/// Web service operation 'QueryDeviceUseingInfo' (returns error code or SOAP_OK)
	virtual	int QueryDeviceUseingInfo(_Xdmrtm__QueryDeviceUseingInfo *Xdmrtm__QueryDeviceUseingInfo, _Xdmrtm__QueryDeviceUseingInfoResponse *Xdmrtm__QueryDeviceUseingInfoResponse);

	/// Web service operation 'QueryDeviceUseingInfoByDevice' (returns error code or SOAP_OK)
	virtual	int QueryDeviceUseingInfoByDevice(_Xdmrtm__QueryDeviceUseingInfoByDevice *Xdmrtm__QueryDeviceUseingInfoByDevice, _Xdmrtm__QueryDeviceUseingInfoByDeviceResponse *Xdmrtm__QueryDeviceUseingInfoByDeviceResponse);

	/// Web service operation 'QueryDeviceUseingInfoByUser' (returns error code or SOAP_OK)
	virtual	int QueryDeviceUseingInfoByUser(_Xdmrtm__QueryDeviceUseingInfoByUser *Xdmrtm__QueryDeviceUseingInfoByUser, _Xdmrtm__QueryDeviceUseingInfoByUserResponse *Xdmrtm__QueryDeviceUseingInfoByUserResponse);

	/// Web service operation 'QueryFreqLayout' (returns error code or SOAP_OK)
	virtual	int QueryFreqLayout(_Xdmrtm__QueryFreqLayout *Xdmrtm__QueryFreqLayout, _Xdmrtm__QueryFreqLayoutResponse *Xdmrtm__QueryFreqLayoutResponse);

	/// Web service operation 'QueryCurExecPlanTaskID' (returns error code or SOAP_OK)
	virtual	int QueryCurExecPlanTaskID(_Xdmrtm__QueryCurExecPlanTaskID *Xdmrtm__QueryCurExecPlanTaskID, _Xdmrtm__QueryCurExecPlanTaskIDResponse *Xdmrtm__QueryCurExecPlanTaskIDResponse);

	/// Web service operation 'QueryPlanTask' (returns error code or SOAP_OK)
	virtual	int QueryPlanTask(_Xdmrtm__QueryPlanTask *Xdmrtm__QueryPlanTask, _Xdmrtm__QueryPlanTaskResponse *Xdmrtm__QueryPlanTaskResponse);

	/// Web service operation 'QueryCurExecPlanTask' (returns error code or SOAP_OK)
	virtual	int QueryCurExecPlanTask(_Xdmrtm__QueryCurExecPlanTask *Xdmrtm__QueryCurExecPlanTask, _Xdmrtm__QueryCurExecPlanTaskResponse *Xdmrtm__QueryCurExecPlanTaskResponse);

	/// Web service operation 'StartPlanTask' (returns error code or SOAP_OK)
	virtual	int StartPlanTask(_Xdmrtm__StartPlanTask *Xdmrtm__StartPlanTask, _Xdmrtm__StartPlanTaskResponse *Xdmrtm__StartPlanTaskResponse);

	/// Web service operation 'StopPlanTask' (returns error code or SOAP_OK)
	virtual	int StopPlanTask(_Xdmrtm__StopPlanTask *Xdmrtm__StopPlanTask, _Xdmrtm__StopPlanTaskResponse *Xdmrtm__StopPlanTaskResponse);

	/// Web service operation 'SuspendPlanTask' (returns error code or SOAP_OK)
	virtual	int SuspendPlanTask(_Xdmrtm__SuspendPlanTask *Xdmrtm__SuspendPlanTask, _Xdmrtm__SuspendPlanTaskResponse *Xdmrtm__SuspendPlanTaskResponse);

	/// Web service operation 'ResumePlanTask' (returns error code or SOAP_OK)
	virtual	int ResumePlanTask(_Xdmrtm__ResumePlanTask *Xdmrtm__ResumePlanTask, _Xdmrtm__ResumePlanTaskResponse *Xdmrtm__ResumePlanTaskResponse);

	/// Web service operation 'SubmitPlanTaskLog' (returns error code or SOAP_OK)
	virtual	int SubmitPlanTaskLog(_Xdmrtm__SubmitPlanTaskLog *Xdmrtm__SubmitPlanTaskLog, _Xdmrtm__SubmitPlanTaskLogResponse *Xdmrtm__SubmitPlanTaskLogResponse);

	/// Web service operation 'SubmitMonAnalysisReport' (returns error code or SOAP_OK)
	virtual	int SubmitMonAnalysisReport(_Xdmrtm__SubmitMonAnalysisReport *Xdmrtm__SubmitMonAnalysisReport, _Xdmrtm__SubmitMonAnalysisReportResponse *Xdmrtm__SubmitMonAnalysisReportResponse);

	/// Web service operation 'QueryMonAnalysisReport' (returns error code or SOAP_OK)
	virtual	int QueryMonAnalysisReport(_Xdmrtm__QueryMonAnalysisReport *Xdmrtm__QueryMonAnalysisReport, _Xdmrtm__QueryMonAnalysisReportResponse *Xdmrtm__QueryMonAnalysisReportResponse);

	/// Web service operation 'QueryMonAnalysisReportAttachment' (returns error code or SOAP_OK)
	virtual	int QueryMonAnalysisReportAttachment(_Xdmrtm__QueryMonAnalysisReportAttachment *Xdmrtm__QueryMonAnalysisReportAttachment, _Xdmrtm__QueryMonAnalysisReportAttachmentResponse *Xdmrtm__QueryMonAnalysisReportAttachmentResponse);

	/// Web service operation 'DownloadMonAnalysisReportAttachment' (returns error code or SOAP_OK)
	virtual	int DownloadMonAnalysisReportAttachment(_Xdmrtm__DownloadMonAnalysisReportAttachment *Xdmrtm__DownloadMonAnalysisReportAttachment, _Xdmrtm__DownloadMonAnalysisReportAttachmentResponse *Xdmrtm__DownloadMonAnalysisReportAttachmentResponse);

	/// Web service operation 'IsAnalysisReport' (returns error code or SOAP_OK)
	virtual	int IsAnalysisReport(_Xdmrtm__IsAnalysisReport *Xdmrtm__IsAnalysisReport, _Xdmrtm__IsAnalysisReportResponse *Xdmrtm__IsAnalysisReportResponse);

	/// Web service operation 'DeleteMonAnalysisReport' (returns error code or SOAP_OK)
	virtual	int DeleteMonAnalysisReport(_Xdmrtm__DeleteMonAnalysisReport *Xdmrtm__DeleteMonAnalysisReport, _Xdmrtm__DeleteMonAnalysisResponse *Xdmrtm__DeleteMonAnalysisResponse);

	/// Web service operation 'SubmitAlarmInfo' (returns error code or SOAP_OK)
	virtual	int SubmitAlarmInfo(_Xdmrtm__SubmitAlarmInfo *Xdmrtm__SubmitAlarmInfo, _Xdmrtm__SubmitAlarmInfoResponse *Xdmrtm__SubmitAlarmInfoResponse);
};

} // namespace Xdmrtm

#endif
