/* BsdsysserviceBSDSYSSoap12Proxy.h
   Generated by gSOAP 2.8.2 from Bsdsysservice.h
   Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef BsdsysserviceBSDSYSSoap12Proxy_H
#define BsdsysserviceBSDSYSSoap12Proxy_H
#include "BsdsysserviceH.h"

namespace Bsdsysservice {

class SOAP_CMAC BSDSYSSoap12Proxy
{ public:
	struct soap *soap;
	bool own;
	/// Endpoint URL of service 'BSDSYSSoap12Proxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	BSDSYSSoap12Proxy();
	/// Constructor to use/share an engine state
	BSDSYSSoap12Proxy(struct soap*);
	/// Constructor with endpoint URL
	BSDSYSSoap12Proxy(const char *url);
	/// Constructor with engine input+output mode control
	BSDSYSSoap12Proxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	BSDSYSSoap12Proxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	BSDSYSSoap12Proxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~BSDSYSSoap12Proxy();
	/// Initializer used by constructors
	virtual	void BSDSYSSoap12Proxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'VerifyUser' (returns error code or SOAP_OK)
	virtual	int VerifyUser(_Bsdsysservice__VerifyUser *Bsdsysservice__VerifyUser, _Bsdsysservice__VerifyUserResponse *Bsdsysservice__VerifyUserResponse);

	/// Web service operation 'GetUsersForApple' (returns error code or SOAP_OK)
	virtual	int GetUsersForApple(_Bsdsysservice__GetUsersForApple *Bsdsysservice__GetUsersForApple, _Bsdsysservice__GetUsersForAppleResponse *Bsdsysservice__GetUsersForAppleResponse);

	/// Web service operation 'VerifyFunction' (returns error code or SOAP_OK)
	virtual	int VerifyFunction(_Bsdsysservice__VerifyFunction *Bsdsysservice__VerifyFunction, _Bsdsysservice__VerifyFunctionResponse *Bsdsysservice__VerifyFunctionResponse);

	/// Web service operation 'GetServerTime' (returns error code or SOAP_OK)
	virtual	int GetServerTime(_Bsdsysservice__GetServerTime *Bsdsysservice__GetServerTime, _Bsdsysservice__GetServerTimeResponse *Bsdsysservice__GetServerTimeResponse);

	/// Web service operation 'GetAppSetting' (returns error code or SOAP_OK)
	virtual	int GetAppSetting(_Bsdsysservice__GetAppSetting *Bsdsysservice__GetAppSetting, _Bsdsysservice__GetAppSettingResponse *Bsdsysservice__GetAppSettingResponse);

	/// Web service operation 'GetConnString' (returns error code or SOAP_OK)
	virtual	int GetConnString(_Bsdsysservice__GetConnString *Bsdsysservice__GetConnString, _Bsdsysservice__GetConnStringResponse *Bsdsysservice__GetConnStringResponse);

	/// Web service operation 'AlertMsgDirect' (returns error code or SOAP_OK)
	virtual	int AlertMsgDirect(_Bsdsysservice__AlertMsgDirect *Bsdsysservice__AlertMsgDirect, _Bsdsysservice__AlertMsgDirectResponse *Bsdsysservice__AlertMsgDirectResponse);

	/// Web service operation 'GetUnSendMsg' (returns error code or SOAP_OK)
	virtual	int GetUnSendMsg(_Bsdsysservice__GetUnSendMsg *Bsdsysservice__GetUnSendMsg, _Bsdsysservice__GetUnSendMsgResponse *Bsdsysservice__GetUnSendMsgResponse);

	/// Web service operation 'WriteLog' (returns error code or SOAP_OK)
	virtual	int WriteLog(_Bsdsysservice__WriteLog *Bsdsysservice__WriteLog, _Bsdsysservice__WriteLogResponse *Bsdsysservice__WriteLogResponse);

	/// Web service operation 'GetMobileByUserId' (returns error code or SOAP_OK)
	virtual	int GetMobileByUserId(_Bsdsysservice__GetMobileByUserId *Bsdsysservice__GetMobileByUserId, _Bsdsysservice__GetMobileByUserIdResponse *Bsdsysservice__GetMobileByUserIdResponse);

	/// Web service operation 'GetFunctionsByUserId' (returns error code or SOAP_OK)
	virtual	int GetFunctionsByUserId(_Bsdsysservice__GetFunctionsByUserId *Bsdsysservice__GetFunctionsByUserId, _Bsdsysservice__GetFunctionsByUserIdResponse *Bsdsysservice__GetFunctionsByUserIdResponse);

	/// Web service operation 'GetFunctions3' (returns error code or SOAP_OK)
	virtual	int GetFunctions3(_Bsdsysservice__GetFunctions3 *Bsdsysservice__GetFunctions3, _Bsdsysservice__GetFunctions3Response *Bsdsysservice__GetFunctions3Response);

	/// Web service operation 'GetRegions' (returns error code or SOAP_OK)
	virtual	int GetRegions(_Bsdsysservice__GetRegions *Bsdsysservice__GetRegions, _Bsdsysservice__GetRegionsResponse *Bsdsysservice__GetRegionsResponse);

	/// Web service operation 'GetRegions3' (returns error code or SOAP_OK)
	virtual	int GetRegions3(_Bsdsysservice__GetRegions3 *Bsdsysservice__GetRegions3, _Bsdsysservice__GetRegions3Response *Bsdsysservice__GetRegions3Response);

	/// Web service operation 'GetUserList3' (returns error code or SOAP_OK)
	virtual	int GetUserList3(_Bsdsysservice__GetUserList3 *Bsdsysservice__GetUserList3, _Bsdsysservice__GetUserList3Response *Bsdsysservice__GetUserList3Response);

	/// Web service operation 'GetDepartmentList3' (returns error code or SOAP_OK)
	virtual	int GetDepartmentList3(_Bsdsysservice__GetDepartmentList3 *Bsdsysservice__GetDepartmentList3, _Bsdsysservice__GetDepartmentList3Response *Bsdsysservice__GetDepartmentList3Response);

	/// Web service operation 'GetAllUserID' (returns error code or SOAP_OK)
	virtual	int GetAllUserID(_Bsdsysservice__GetAllUserID *Bsdsysservice__GetAllUserID, _Bsdsysservice__GetAllUserIDResponse *Bsdsysservice__GetAllUserIDResponse);

	/// Web service operation 'GetUserList' (returns error code or SOAP_OK)
	virtual	int GetUserList(_Bsdsysservice__GetUserList *Bsdsysservice__GetUserList, _Bsdsysservice__GetUserListResponse *Bsdsysservice__GetUserListResponse);
};

} // namespace Bsdsysservice

#endif
