/* XdmrtmXdmrtmProxy.cpp
   Generated by gSOAP 2.8.2 from Xdmrtm.h
   Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#include "XdmrtmXdmrtmProxy.h"

namespace Xdmrtm {

XdmrtmProxy::XdmrtmProxy()
{	this->soap = soap_new();
	this->own = true;
	XdmrtmProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

XdmrtmProxy::XdmrtmProxy(struct soap *_soap)
{	this->soap = _soap;
	this->own = false;
	XdmrtmProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

XdmrtmProxy::XdmrtmProxy(const char *url)
{	this->soap = soap_new();
	this->own = true;
	XdmrtmProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

XdmrtmProxy::XdmrtmProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	XdmrtmProxy_init(iomode, iomode);
}

XdmrtmProxy::XdmrtmProxy(const char *url, soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	XdmrtmProxy_init(iomode, iomode);
	soap_endpoint = url;
}

XdmrtmProxy::XdmrtmProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->own = true;
	XdmrtmProxy_init(imode, omode);
}

XdmrtmProxy::~XdmrtmProxy()
{	if (this->own)
		soap_free(this->soap);
}

void XdmrtmProxy::XdmrtmProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://www.w3.org/2003/05/soap-envelope", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://www.w3.org/2003/05/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"Xdmrtm", "urn:Xdmrtm", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
}

void XdmrtmProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void XdmrtmProxy::soap_noheader()
{	this->soap->header = NULL;
}

const SOAP_ENV__Fault *XdmrtmProxy::soap_fault()
{	return this->soap->fault;
}

const char *XdmrtmProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *XdmrtmProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int XdmrtmProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

void XdmrtmProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
void XdmrtmProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}

char *XdmrtmProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int XdmrtmProxy::QueryRefStationType(_Xdmrtm__QueryRefStationType *Xdmrtm__QueryRefStationType, _Xdmrtm__QueryRefStationTypeResponse *Xdmrtm__QueryRefStationTypeResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryRefStationType soap_tmp___Xdmrtm__QueryRefStationType;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryRefStationType.Xdmrtm__QueryRefStationType = Xdmrtm__QueryRefStationType;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryRefStationType(soap, &soap_tmp___Xdmrtm__QueryRefStationType);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryRefStationType(soap, &soap_tmp___Xdmrtm__QueryRefStationType, "-Xdmrtm:QueryRefStationType", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryRefStationType(soap, &soap_tmp___Xdmrtm__QueryRefStationType, "-Xdmrtm:QueryRefStationType", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryRefStationTypeResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryRefStationTypeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryRefStationTypeResponse->soap_get(soap, "Xdmrtm:QueryRefStationTypeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryRefDeviceType(_Xdmrtm__QueryRefDeviceType *Xdmrtm__QueryRefDeviceType, _Xdmrtm__QueryRefDeviceTypeResponse *Xdmrtm__QueryRefDeviceTypeResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryRefDeviceType soap_tmp___Xdmrtm__QueryRefDeviceType;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryRefDeviceType.Xdmrtm__QueryRefDeviceType = Xdmrtm__QueryRefDeviceType;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryRefDeviceType(soap, &soap_tmp___Xdmrtm__QueryRefDeviceType);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryRefDeviceType(soap, &soap_tmp___Xdmrtm__QueryRefDeviceType, "-Xdmrtm:QueryRefDeviceType", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryRefDeviceType(soap, &soap_tmp___Xdmrtm__QueryRefDeviceType, "-Xdmrtm:QueryRefDeviceType", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryRefDeviceTypeResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryRefDeviceTypeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryRefDeviceTypeResponse->soap_get(soap, "Xdmrtm:QueryRefDeviceTypeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryRefDeviceProtocolType(_Xdmrtm__QueryRefDeviceProtocolType *Xdmrtm__QueryRefDeviceProtocolType, _Xdmrtm__QueryRefDeviceProtocolTypeResponse *Xdmrtm__QueryRefDeviceProtocolTypeResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryRefDeviceProtocolType soap_tmp___Xdmrtm__QueryRefDeviceProtocolType;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryRefDeviceProtocolType.Xdmrtm__QueryRefDeviceProtocolType = Xdmrtm__QueryRefDeviceProtocolType;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryRefDeviceProtocolType(soap, &soap_tmp___Xdmrtm__QueryRefDeviceProtocolType);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryRefDeviceProtocolType(soap, &soap_tmp___Xdmrtm__QueryRefDeviceProtocolType, "-Xdmrtm:QueryRefDeviceProtocolType", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryRefDeviceProtocolType(soap, &soap_tmp___Xdmrtm__QueryRefDeviceProtocolType, "-Xdmrtm:QueryRefDeviceProtocolType", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryRefDeviceProtocolTypeResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryRefDeviceProtocolTypeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryRefDeviceProtocolTypeResponse->soap_get(soap, "Xdmrtm:QueryRefDeviceProtocolTypeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryRefDeviceModel(_Xdmrtm__QueryRefDeviceModel *Xdmrtm__QueryRefDeviceModel, _Xdmrtm__QueryRefDeviceModelResponse *Xdmrtm__QueryRefDeviceModelResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryRefDeviceModel soap_tmp___Xdmrtm__QueryRefDeviceModel;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryRefDeviceModel.Xdmrtm__QueryRefDeviceModel = Xdmrtm__QueryRefDeviceModel;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryRefDeviceModel(soap, &soap_tmp___Xdmrtm__QueryRefDeviceModel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryRefDeviceModel(soap, &soap_tmp___Xdmrtm__QueryRefDeviceModel, "-Xdmrtm:QueryRefDeviceModel", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryRefDeviceModel(soap, &soap_tmp___Xdmrtm__QueryRefDeviceModel, "-Xdmrtm:QueryRefDeviceModel", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryRefDeviceModelResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryRefDeviceModelResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryRefDeviceModelResponse->soap_get(soap, "Xdmrtm:QueryRefDeviceModelResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryRefDeviceFunc(_Xdmrtm__QueryRefDeviceFunc *Xdmrtm__QueryRefDeviceFunc, _Xdmrtm__QueryRefDeviceFuncResponse *Xdmrtm__QueryRefDeviceFuncResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryRefDeviceFunc soap_tmp___Xdmrtm__QueryRefDeviceFunc;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryRefDeviceFunc.Xdmrtm__QueryRefDeviceFunc = Xdmrtm__QueryRefDeviceFunc;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryRefDeviceFunc(soap, &soap_tmp___Xdmrtm__QueryRefDeviceFunc);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryRefDeviceFunc(soap, &soap_tmp___Xdmrtm__QueryRefDeviceFunc, "-Xdmrtm:QueryRefDeviceFunc", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryRefDeviceFunc(soap, &soap_tmp___Xdmrtm__QueryRefDeviceFunc, "-Xdmrtm:QueryRefDeviceFunc", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryRefDeviceFuncResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryRefDeviceFuncResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryRefDeviceFuncResponse->soap_get(soap, "Xdmrtm:QueryRefDeviceFuncResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryRefDeviceModelFuncParam(_Xdmrtm__QueryRefDeviceModelFuncParam *Xdmrtm__QueryRefDeviceModelFuncParam, _Xdmrtm__QueryRefDeviceModelFuncParamResponse *Xdmrtm__QueryRefDeviceModelFuncParamResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryRefDeviceModelFuncParam soap_tmp___Xdmrtm__QueryRefDeviceModelFuncParam;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryRefDeviceModelFuncParam.Xdmrtm__QueryRefDeviceModelFuncParam = Xdmrtm__QueryRefDeviceModelFuncParam;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryRefDeviceModelFuncParam(soap, &soap_tmp___Xdmrtm__QueryRefDeviceModelFuncParam);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryRefDeviceModelFuncParam(soap, &soap_tmp___Xdmrtm__QueryRefDeviceModelFuncParam, "-Xdmrtm:QueryRefDeviceModelFuncParam", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryRefDeviceModelFuncParam(soap, &soap_tmp___Xdmrtm__QueryRefDeviceModelFuncParam, "-Xdmrtm:QueryRefDeviceModelFuncParam", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryRefDeviceModelFuncParamResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryRefDeviceModelFuncParamResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryRefDeviceModelFuncParamResponse->soap_get(soap, "Xdmrtm:QueryRefDeviceModelFuncParamResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryMonOrganization(_Xdmrtm__QueryMonOrganization *Xdmrtm__QueryMonOrganization, _Xdmrtm__QueryMonOrganizationResponse *Xdmrtm__QueryMonOrganizationResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryMonOrganization soap_tmp___Xdmrtm__QueryMonOrganization;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryMonOrganization.Xdmrtm__QueryMonOrganization = Xdmrtm__QueryMonOrganization;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryMonOrganization(soap, &soap_tmp___Xdmrtm__QueryMonOrganization);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryMonOrganization(soap, &soap_tmp___Xdmrtm__QueryMonOrganization, "-Xdmrtm:QueryMonOrganization", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryMonOrganization(soap, &soap_tmp___Xdmrtm__QueryMonOrganization, "-Xdmrtm:QueryMonOrganization", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryMonOrganizationResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryMonOrganizationResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryMonOrganizationResponse->soap_get(soap, "Xdmrtm:QueryMonOrganizationResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryMonControlCenter(_Xdmrtm__QueryMonControlCenter *Xdmrtm__QueryMonControlCenter, _Xdmrtm__QueryMonControlCenterResponse *Xdmrtm__QueryMonControlCenterResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryMonControlCenter soap_tmp___Xdmrtm__QueryMonControlCenter;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryMonControlCenter.Xdmrtm__QueryMonControlCenter = Xdmrtm__QueryMonControlCenter;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryMonControlCenter(soap, &soap_tmp___Xdmrtm__QueryMonControlCenter);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryMonControlCenter(soap, &soap_tmp___Xdmrtm__QueryMonControlCenter, "-Xdmrtm:QueryMonControlCenter", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryMonControlCenter(soap, &soap_tmp___Xdmrtm__QueryMonControlCenter, "-Xdmrtm:QueryMonControlCenter", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryMonControlCenterResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryMonControlCenterResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryMonControlCenterResponse->soap_get(soap, "Xdmrtm:QueryMonControlCenterResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryStation(_Xdmrtm__QueryStation *Xdmrtm__QueryStation, _Xdmrtm__QueryStationResponse *Xdmrtm__QueryStationResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryStation soap_tmp___Xdmrtm__QueryStation;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryStation.Xdmrtm__QueryStation = Xdmrtm__QueryStation;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryStation(soap, &soap_tmp___Xdmrtm__QueryStation);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryStation(soap, &soap_tmp___Xdmrtm__QueryStation, "-Xdmrtm:QueryStation", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryStation(soap, &soap_tmp___Xdmrtm__QueryStation, "-Xdmrtm:QueryStation", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryStationResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryStationResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryStationResponse->soap_get(soap, "Xdmrtm:QueryStationResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryDevice(_Xdmrtm__QueryDevice *Xdmrtm__QueryDevice, _Xdmrtm__QueryDeviceResponse *Xdmrtm__QueryDeviceResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryDevice soap_tmp___Xdmrtm__QueryDevice;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryDevice.Xdmrtm__QueryDevice = Xdmrtm__QueryDevice;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryDevice(soap, &soap_tmp___Xdmrtm__QueryDevice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryDevice(soap, &soap_tmp___Xdmrtm__QueryDevice, "-Xdmrtm:QueryDevice", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryDevice(soap, &soap_tmp___Xdmrtm__QueryDevice, "-Xdmrtm:QueryDevice", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryDeviceResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryDeviceResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryDeviceResponse->soap_get(soap, "Xdmrtm:QueryDeviceResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryRNC(_Xdmrtm__QueryRNC *Xdmrtm__QueryRNC, _Xdmrtm__QueryRNCResponse *Xdmrtm__QueryRNCResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryRNC soap_tmp___Xdmrtm__QueryRNC;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryRNC.Xdmrtm__QueryRNC = Xdmrtm__QueryRNC;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryRNC(soap, &soap_tmp___Xdmrtm__QueryRNC);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryRNC(soap, &soap_tmp___Xdmrtm__QueryRNC, "-Xdmrtm:QueryRNC", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryRNC(soap, &soap_tmp___Xdmrtm__QueryRNC, "-Xdmrtm:QueryRNC", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryRNCResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryRNCResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryRNCResponse->soap_get(soap, "Xdmrtm:QueryRNCResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryAnt(_Xdmrtm__QueryAnt *Xdmrtm__QueryAnt, _Xdmrtm__QueryAntResponse *Xdmrtm__QueryAntResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryAnt soap_tmp___Xdmrtm__QueryAnt;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryAnt.Xdmrtm__QueryAnt = Xdmrtm__QueryAnt;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryAnt(soap, &soap_tmp___Xdmrtm__QueryAnt);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryAnt(soap, &soap_tmp___Xdmrtm__QueryAnt, "-Xdmrtm:QueryAnt", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryAnt(soap, &soap_tmp___Xdmrtm__QueryAnt, "-Xdmrtm:QueryAnt", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryAntResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryAntResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryAntResponse->soap_get(soap, "Xdmrtm:QueryAntResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryDeviceFunc(_Xdmrtm__QueryDeviceFunc *Xdmrtm__QueryDeviceFunc, _Xdmrtm__QueryDeviceFuncResponse *Xdmrtm__QueryDeviceFuncResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryDeviceFunc soap_tmp___Xdmrtm__QueryDeviceFunc;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryDeviceFunc.Xdmrtm__QueryDeviceFunc = Xdmrtm__QueryDeviceFunc;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryDeviceFunc(soap, &soap_tmp___Xdmrtm__QueryDeviceFunc);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryDeviceFunc(soap, &soap_tmp___Xdmrtm__QueryDeviceFunc, "-Xdmrtm:QueryDeviceFunc", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryDeviceFunc(soap, &soap_tmp___Xdmrtm__QueryDeviceFunc, "-Xdmrtm:QueryDeviceFunc", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryDeviceFuncResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryDeviceFuncResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryDeviceFuncResponse->soap_get(soap, "Xdmrtm:QueryDeviceFuncResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryDeviceFuncAnt(_Xdmrtm__QueryDeviceFuncAnt *Xdmrtm__QueryDeviceFuncAnt, _Xdmrtm__QueryDeviceFuncAntResponse *Xdmrtm__QueryDeviceFuncAntResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryDeviceFuncAnt soap_tmp___Xdmrtm__QueryDeviceFuncAnt;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryDeviceFuncAnt.Xdmrtm__QueryDeviceFuncAnt = Xdmrtm__QueryDeviceFuncAnt;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryDeviceFuncAnt(soap, &soap_tmp___Xdmrtm__QueryDeviceFuncAnt);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryDeviceFuncAnt(soap, &soap_tmp___Xdmrtm__QueryDeviceFuncAnt, "-Xdmrtm:QueryDeviceFuncAnt", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryDeviceFuncAnt(soap, &soap_tmp___Xdmrtm__QueryDeviceFuncAnt, "-Xdmrtm:QueryDeviceFuncAnt", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryDeviceFuncAntResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryDeviceFuncAntResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryDeviceFuncAntResponse->soap_get(soap, "Xdmrtm:QueryDeviceFuncAntResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryUserLicenseStation(_Xdmrtm__QueryUserLicenseStation *Xdmrtm__QueryUserLicenseStation, _Xdmrtm__QueryUserLicenseStationResponse *Xdmrtm__QueryUserLicenseStationResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryUserLicenseStation soap_tmp___Xdmrtm__QueryUserLicenseStation;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryUserLicenseStation.Xdmrtm__QueryUserLicenseStation = Xdmrtm__QueryUserLicenseStation;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryUserLicenseStation(soap, &soap_tmp___Xdmrtm__QueryUserLicenseStation);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryUserLicenseStation(soap, &soap_tmp___Xdmrtm__QueryUserLicenseStation, "-Xdmrtm:QueryUserLicenseStation", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryUserLicenseStation(soap, &soap_tmp___Xdmrtm__QueryUserLicenseStation, "-Xdmrtm:QueryUserLicenseStation", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryUserLicenseStationResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryUserLicenseStationResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryUserLicenseStationResponse->soap_get(soap, "Xdmrtm:QueryUserLicenseStationResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::AllocLoadbalancingServer(_Xdmrtm__AllocLoadbalancingServer *Xdmrtm__AllocLoadbalancingServer, _Xdmrtm__AllocLoadbalancingServerResponse *Xdmrtm__AllocLoadbalancingServerResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__AllocLoadbalancingServer soap_tmp___Xdmrtm__AllocLoadbalancingServer;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__AllocLoadbalancingServer.Xdmrtm__AllocLoadbalancingServer = Xdmrtm__AllocLoadbalancingServer;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__AllocLoadbalancingServer(soap, &soap_tmp___Xdmrtm__AllocLoadbalancingServer);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__AllocLoadbalancingServer(soap, &soap_tmp___Xdmrtm__AllocLoadbalancingServer, "-Xdmrtm:AllocLoadbalancingServer", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__AllocLoadbalancingServer(soap, &soap_tmp___Xdmrtm__AllocLoadbalancingServer, "-Xdmrtm:AllocLoadbalancingServer", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__AllocLoadbalancingServerResponse)
		return soap_closesock(soap);
	Xdmrtm__AllocLoadbalancingServerResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__AllocLoadbalancingServerResponse->soap_get(soap, "Xdmrtm:AllocLoadbalancingServerResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::SubmitDeviceUsedLog(_Xdmrtm__SubmitDeviceUsedLog *Xdmrtm__SubmitDeviceUsedLog, _Xdmrtm__SubmitDeviceUsedLogResponse *Xdmrtm__SubmitDeviceUsedLogResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__SubmitDeviceUsedLog soap_tmp___Xdmrtm__SubmitDeviceUsedLog;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__SubmitDeviceUsedLog.Xdmrtm__SubmitDeviceUsedLog = Xdmrtm__SubmitDeviceUsedLog;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__SubmitDeviceUsedLog(soap, &soap_tmp___Xdmrtm__SubmitDeviceUsedLog);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__SubmitDeviceUsedLog(soap, &soap_tmp___Xdmrtm__SubmitDeviceUsedLog, "-Xdmrtm:SubmitDeviceUsedLog", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__SubmitDeviceUsedLog(soap, &soap_tmp___Xdmrtm__SubmitDeviceUsedLog, "-Xdmrtm:SubmitDeviceUsedLog", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__SubmitDeviceUsedLogResponse)
		return soap_closesock(soap);
	Xdmrtm__SubmitDeviceUsedLogResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__SubmitDeviceUsedLogResponse->soap_get(soap, "Xdmrtm:SubmitDeviceUsedLogResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryDeviceUseingInfo(_Xdmrtm__QueryDeviceUseingInfo *Xdmrtm__QueryDeviceUseingInfo, _Xdmrtm__QueryDeviceUseingInfoResponse *Xdmrtm__QueryDeviceUseingInfoResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryDeviceUseingInfo soap_tmp___Xdmrtm__QueryDeviceUseingInfo;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryDeviceUseingInfo.Xdmrtm__QueryDeviceUseingInfo = Xdmrtm__QueryDeviceUseingInfo;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryDeviceUseingInfo(soap, &soap_tmp___Xdmrtm__QueryDeviceUseingInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryDeviceUseingInfo(soap, &soap_tmp___Xdmrtm__QueryDeviceUseingInfo, "-Xdmrtm:QueryDeviceUseingInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryDeviceUseingInfo(soap, &soap_tmp___Xdmrtm__QueryDeviceUseingInfo, "-Xdmrtm:QueryDeviceUseingInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryDeviceUseingInfoResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryDeviceUseingInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryDeviceUseingInfoResponse->soap_get(soap, "Xdmrtm:QueryDeviceUseingInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryDeviceUseingInfoByDevice(_Xdmrtm__QueryDeviceUseingInfoByDevice *Xdmrtm__QueryDeviceUseingInfoByDevice, _Xdmrtm__QueryDeviceUseingInfoByDeviceResponse *Xdmrtm__QueryDeviceUseingInfoByDeviceResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryDeviceUseingInfoByDevice soap_tmp___Xdmrtm__QueryDeviceUseingInfoByDevice;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryDeviceUseingInfoByDevice.Xdmrtm__QueryDeviceUseingInfoByDevice = Xdmrtm__QueryDeviceUseingInfoByDevice;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryDeviceUseingInfoByDevice(soap, &soap_tmp___Xdmrtm__QueryDeviceUseingInfoByDevice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryDeviceUseingInfoByDevice(soap, &soap_tmp___Xdmrtm__QueryDeviceUseingInfoByDevice, "-Xdmrtm:QueryDeviceUseingInfoByDevice", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryDeviceUseingInfoByDevice(soap, &soap_tmp___Xdmrtm__QueryDeviceUseingInfoByDevice, "-Xdmrtm:QueryDeviceUseingInfoByDevice", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryDeviceUseingInfoByDeviceResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryDeviceUseingInfoByDeviceResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryDeviceUseingInfoByDeviceResponse->soap_get(soap, "Xdmrtm:QueryDeviceUseingInfoByDeviceResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryDeviceUseingInfoByUser(_Xdmrtm__QueryDeviceUseingInfoByUser *Xdmrtm__QueryDeviceUseingInfoByUser, _Xdmrtm__QueryDeviceUseingInfoByUserResponse *Xdmrtm__QueryDeviceUseingInfoByUserResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryDeviceUseingInfoByUser soap_tmp___Xdmrtm__QueryDeviceUseingInfoByUser;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryDeviceUseingInfoByUser.Xdmrtm__QueryDeviceUseingInfoByUser = Xdmrtm__QueryDeviceUseingInfoByUser;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryDeviceUseingInfoByUser(soap, &soap_tmp___Xdmrtm__QueryDeviceUseingInfoByUser);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryDeviceUseingInfoByUser(soap, &soap_tmp___Xdmrtm__QueryDeviceUseingInfoByUser, "-Xdmrtm:QueryDeviceUseingInfoByUser", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryDeviceUseingInfoByUser(soap, &soap_tmp___Xdmrtm__QueryDeviceUseingInfoByUser, "-Xdmrtm:QueryDeviceUseingInfoByUser", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryDeviceUseingInfoByUserResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryDeviceUseingInfoByUserResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryDeviceUseingInfoByUserResponse->soap_get(soap, "Xdmrtm:QueryDeviceUseingInfoByUserResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryFreqLayout(_Xdmrtm__QueryFreqLayout *Xdmrtm__QueryFreqLayout, _Xdmrtm__QueryFreqLayoutResponse *Xdmrtm__QueryFreqLayoutResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryFreqLayout soap_tmp___Xdmrtm__QueryFreqLayout;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryFreqLayout.Xdmrtm__QueryFreqLayout = Xdmrtm__QueryFreqLayout;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryFreqLayout(soap, &soap_tmp___Xdmrtm__QueryFreqLayout);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryFreqLayout(soap, &soap_tmp___Xdmrtm__QueryFreqLayout, "-Xdmrtm:QueryFreqLayout", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryFreqLayout(soap, &soap_tmp___Xdmrtm__QueryFreqLayout, "-Xdmrtm:QueryFreqLayout", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryFreqLayoutResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryFreqLayoutResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryFreqLayoutResponse->soap_get(soap, "Xdmrtm:QueryFreqLayoutResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryCurExecPlanTaskID(_Xdmrtm__QueryCurExecPlanTaskID *Xdmrtm__QueryCurExecPlanTaskID, _Xdmrtm__QueryCurExecPlanTaskIDResponse *Xdmrtm__QueryCurExecPlanTaskIDResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryCurExecPlanTaskID soap_tmp___Xdmrtm__QueryCurExecPlanTaskID;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryCurExecPlanTaskID.Xdmrtm__QueryCurExecPlanTaskID = Xdmrtm__QueryCurExecPlanTaskID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryCurExecPlanTaskID(soap, &soap_tmp___Xdmrtm__QueryCurExecPlanTaskID);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryCurExecPlanTaskID(soap, &soap_tmp___Xdmrtm__QueryCurExecPlanTaskID, "-Xdmrtm:QueryCurExecPlanTaskID", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryCurExecPlanTaskID(soap, &soap_tmp___Xdmrtm__QueryCurExecPlanTaskID, "-Xdmrtm:QueryCurExecPlanTaskID", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryCurExecPlanTaskIDResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryCurExecPlanTaskIDResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryCurExecPlanTaskIDResponse->soap_get(soap, "Xdmrtm:QueryCurExecPlanTaskIDResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryPlanTask(_Xdmrtm__QueryPlanTask *Xdmrtm__QueryPlanTask, _Xdmrtm__QueryPlanTaskResponse *Xdmrtm__QueryPlanTaskResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryPlanTask soap_tmp___Xdmrtm__QueryPlanTask;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryPlanTask.Xdmrtm__QueryPlanTask = Xdmrtm__QueryPlanTask;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryPlanTask(soap, &soap_tmp___Xdmrtm__QueryPlanTask);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryPlanTask(soap, &soap_tmp___Xdmrtm__QueryPlanTask, "-Xdmrtm:QueryPlanTask", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryPlanTask(soap, &soap_tmp___Xdmrtm__QueryPlanTask, "-Xdmrtm:QueryPlanTask", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryPlanTaskResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryPlanTaskResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryPlanTaskResponse->soap_get(soap, "Xdmrtm:QueryPlanTaskResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryCurExecPlanTask(_Xdmrtm__QueryCurExecPlanTask *Xdmrtm__QueryCurExecPlanTask, _Xdmrtm__QueryCurExecPlanTaskResponse *Xdmrtm__QueryCurExecPlanTaskResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryCurExecPlanTask soap_tmp___Xdmrtm__QueryCurExecPlanTask;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryCurExecPlanTask.Xdmrtm__QueryCurExecPlanTask = Xdmrtm__QueryCurExecPlanTask;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryCurExecPlanTask(soap, &soap_tmp___Xdmrtm__QueryCurExecPlanTask);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryCurExecPlanTask(soap, &soap_tmp___Xdmrtm__QueryCurExecPlanTask, "-Xdmrtm:QueryCurExecPlanTask", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryCurExecPlanTask(soap, &soap_tmp___Xdmrtm__QueryCurExecPlanTask, "-Xdmrtm:QueryCurExecPlanTask", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryCurExecPlanTaskResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryCurExecPlanTaskResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryCurExecPlanTaskResponse->soap_get(soap, "Xdmrtm:QueryCurExecPlanTaskResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::StartPlanTask(_Xdmrtm__StartPlanTask *Xdmrtm__StartPlanTask, _Xdmrtm__StartPlanTaskResponse *Xdmrtm__StartPlanTaskResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__StartPlanTask soap_tmp___Xdmrtm__StartPlanTask;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__StartPlanTask.Xdmrtm__StartPlanTask = Xdmrtm__StartPlanTask;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__StartPlanTask(soap, &soap_tmp___Xdmrtm__StartPlanTask);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__StartPlanTask(soap, &soap_tmp___Xdmrtm__StartPlanTask, "-Xdmrtm:StartPlanTask", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__StartPlanTask(soap, &soap_tmp___Xdmrtm__StartPlanTask, "-Xdmrtm:StartPlanTask", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__StartPlanTaskResponse)
		return soap_closesock(soap);
	Xdmrtm__StartPlanTaskResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__StartPlanTaskResponse->soap_get(soap, "Xdmrtm:StartPlanTaskResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::StopPlanTask(_Xdmrtm__StopPlanTask *Xdmrtm__StopPlanTask, _Xdmrtm__StopPlanTaskResponse *Xdmrtm__StopPlanTaskResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__StopPlanTask soap_tmp___Xdmrtm__StopPlanTask;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__StopPlanTask.Xdmrtm__StopPlanTask = Xdmrtm__StopPlanTask;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__StopPlanTask(soap, &soap_tmp___Xdmrtm__StopPlanTask);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__StopPlanTask(soap, &soap_tmp___Xdmrtm__StopPlanTask, "-Xdmrtm:StopPlanTask", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__StopPlanTask(soap, &soap_tmp___Xdmrtm__StopPlanTask, "-Xdmrtm:StopPlanTask", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__StopPlanTaskResponse)
		return soap_closesock(soap);
	Xdmrtm__StopPlanTaskResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__StopPlanTaskResponse->soap_get(soap, "Xdmrtm:StopPlanTaskResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::SuspendPlanTask(_Xdmrtm__SuspendPlanTask *Xdmrtm__SuspendPlanTask, _Xdmrtm__SuspendPlanTaskResponse *Xdmrtm__SuspendPlanTaskResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__SuspendPlanTask soap_tmp___Xdmrtm__SuspendPlanTask;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__SuspendPlanTask.Xdmrtm__SuspendPlanTask = Xdmrtm__SuspendPlanTask;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__SuspendPlanTask(soap, &soap_tmp___Xdmrtm__SuspendPlanTask);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__SuspendPlanTask(soap, &soap_tmp___Xdmrtm__SuspendPlanTask, "-Xdmrtm:SuspendPlanTask", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__SuspendPlanTask(soap, &soap_tmp___Xdmrtm__SuspendPlanTask, "-Xdmrtm:SuspendPlanTask", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__SuspendPlanTaskResponse)
		return soap_closesock(soap);
	Xdmrtm__SuspendPlanTaskResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__SuspendPlanTaskResponse->soap_get(soap, "Xdmrtm:SuspendPlanTaskResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::ResumePlanTask(_Xdmrtm__ResumePlanTask *Xdmrtm__ResumePlanTask, _Xdmrtm__ResumePlanTaskResponse *Xdmrtm__ResumePlanTaskResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__ResumePlanTask soap_tmp___Xdmrtm__ResumePlanTask;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__ResumePlanTask.Xdmrtm__ResumePlanTask = Xdmrtm__ResumePlanTask;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__ResumePlanTask(soap, &soap_tmp___Xdmrtm__ResumePlanTask);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__ResumePlanTask(soap, &soap_tmp___Xdmrtm__ResumePlanTask, "-Xdmrtm:ResumePlanTask", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__ResumePlanTask(soap, &soap_tmp___Xdmrtm__ResumePlanTask, "-Xdmrtm:ResumePlanTask", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__ResumePlanTaskResponse)
		return soap_closesock(soap);
	Xdmrtm__ResumePlanTaskResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__ResumePlanTaskResponse->soap_get(soap, "Xdmrtm:ResumePlanTaskResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::SubmitPlanTaskLog(_Xdmrtm__SubmitPlanTaskLog *Xdmrtm__SubmitPlanTaskLog, _Xdmrtm__SubmitPlanTaskLogResponse *Xdmrtm__SubmitPlanTaskLogResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__SubmitPlanTaskLog soap_tmp___Xdmrtm__SubmitPlanTaskLog;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__SubmitPlanTaskLog.Xdmrtm__SubmitPlanTaskLog = Xdmrtm__SubmitPlanTaskLog;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__SubmitPlanTaskLog(soap, &soap_tmp___Xdmrtm__SubmitPlanTaskLog);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__SubmitPlanTaskLog(soap, &soap_tmp___Xdmrtm__SubmitPlanTaskLog, "-Xdmrtm:SubmitPlanTaskLog", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__SubmitPlanTaskLog(soap, &soap_tmp___Xdmrtm__SubmitPlanTaskLog, "-Xdmrtm:SubmitPlanTaskLog", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__SubmitPlanTaskLogResponse)
		return soap_closesock(soap);
	Xdmrtm__SubmitPlanTaskLogResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__SubmitPlanTaskLogResponse->soap_get(soap, "Xdmrtm:SubmitPlanTaskLogResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::SubmitMonAnalysisReport(_Xdmrtm__SubmitMonAnalysisReport *Xdmrtm__SubmitMonAnalysisReport, _Xdmrtm__SubmitMonAnalysisReportResponse *Xdmrtm__SubmitMonAnalysisReportResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__SubmitMonAnalysisReport soap_tmp___Xdmrtm__SubmitMonAnalysisReport;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__SubmitMonAnalysisReport.Xdmrtm__SubmitMonAnalysisReport = Xdmrtm__SubmitMonAnalysisReport;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__SubmitMonAnalysisReport(soap, &soap_tmp___Xdmrtm__SubmitMonAnalysisReport);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__SubmitMonAnalysisReport(soap, &soap_tmp___Xdmrtm__SubmitMonAnalysisReport, "-Xdmrtm:SubmitMonAnalysisReport", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__SubmitMonAnalysisReport(soap, &soap_tmp___Xdmrtm__SubmitMonAnalysisReport, "-Xdmrtm:SubmitMonAnalysisReport", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__SubmitMonAnalysisReportResponse)
		return soap_closesock(soap);
	Xdmrtm__SubmitMonAnalysisReportResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__SubmitMonAnalysisReportResponse->soap_get(soap, "Xdmrtm:SubmitMonAnalysisReportResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryMonAnalysisReport(_Xdmrtm__QueryMonAnalysisReport *Xdmrtm__QueryMonAnalysisReport, _Xdmrtm__QueryMonAnalysisReportResponse *Xdmrtm__QueryMonAnalysisReportResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryMonAnalysisReport soap_tmp___Xdmrtm__QueryMonAnalysisReport;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryMonAnalysisReport.Xdmrtm__QueryMonAnalysisReport = Xdmrtm__QueryMonAnalysisReport;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryMonAnalysisReport(soap, &soap_tmp___Xdmrtm__QueryMonAnalysisReport);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryMonAnalysisReport(soap, &soap_tmp___Xdmrtm__QueryMonAnalysisReport, "-Xdmrtm:QueryMonAnalysisReport", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryMonAnalysisReport(soap, &soap_tmp___Xdmrtm__QueryMonAnalysisReport, "-Xdmrtm:QueryMonAnalysisReport", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryMonAnalysisReportResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryMonAnalysisReportResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryMonAnalysisReportResponse->soap_get(soap, "Xdmrtm:QueryMonAnalysisReportResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::QueryMonAnalysisReportAttachment(_Xdmrtm__QueryMonAnalysisReportAttachment *Xdmrtm__QueryMonAnalysisReportAttachment, _Xdmrtm__QueryMonAnalysisReportAttachmentResponse *Xdmrtm__QueryMonAnalysisReportAttachmentResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__QueryMonAnalysisReportAttachment soap_tmp___Xdmrtm__QueryMonAnalysisReportAttachment;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__QueryMonAnalysisReportAttachment.Xdmrtm__QueryMonAnalysisReportAttachment = Xdmrtm__QueryMonAnalysisReportAttachment;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__QueryMonAnalysisReportAttachment(soap, &soap_tmp___Xdmrtm__QueryMonAnalysisReportAttachment);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__QueryMonAnalysisReportAttachment(soap, &soap_tmp___Xdmrtm__QueryMonAnalysisReportAttachment, "-Xdmrtm:QueryMonAnalysisReportAttachment", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__QueryMonAnalysisReportAttachment(soap, &soap_tmp___Xdmrtm__QueryMonAnalysisReportAttachment, "-Xdmrtm:QueryMonAnalysisReportAttachment", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__QueryMonAnalysisReportAttachmentResponse)
		return soap_closesock(soap);
	Xdmrtm__QueryMonAnalysisReportAttachmentResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__QueryMonAnalysisReportAttachmentResponse->soap_get(soap, "Xdmrtm:QueryMonAnalysisReportAttachmentResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::DownloadMonAnalysisReportAttachment(_Xdmrtm__DownloadMonAnalysisReportAttachment *Xdmrtm__DownloadMonAnalysisReportAttachment, _Xdmrtm__DownloadMonAnalysisReportAttachmentResponse *Xdmrtm__DownloadMonAnalysisReportAttachmentResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__DownloadMonAnalysisReportAttachment soap_tmp___Xdmrtm__DownloadMonAnalysisReportAttachment;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__DownloadMonAnalysisReportAttachment.Xdmrtm__DownloadMonAnalysisReportAttachment = Xdmrtm__DownloadMonAnalysisReportAttachment;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__DownloadMonAnalysisReportAttachment(soap, &soap_tmp___Xdmrtm__DownloadMonAnalysisReportAttachment);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__DownloadMonAnalysisReportAttachment(soap, &soap_tmp___Xdmrtm__DownloadMonAnalysisReportAttachment, "-Xdmrtm:DownloadMonAnalysisReportAttachment", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__DownloadMonAnalysisReportAttachment(soap, &soap_tmp___Xdmrtm__DownloadMonAnalysisReportAttachment, "-Xdmrtm:DownloadMonAnalysisReportAttachment", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__DownloadMonAnalysisReportAttachmentResponse)
		return soap_closesock(soap);
	Xdmrtm__DownloadMonAnalysisReportAttachmentResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__DownloadMonAnalysisReportAttachmentResponse->soap_get(soap, "Xdmrtm:DownloadMonAnalysisReportAttachmentResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::IsAnalysisReport(_Xdmrtm__IsAnalysisReport *Xdmrtm__IsAnalysisReport, _Xdmrtm__IsAnalysisReportResponse *Xdmrtm__IsAnalysisReportResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__IsAnalysisReport soap_tmp___Xdmrtm__IsAnalysisReport;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__IsAnalysisReport.Xdmrtm__IsAnalysisReport = Xdmrtm__IsAnalysisReport;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__IsAnalysisReport(soap, &soap_tmp___Xdmrtm__IsAnalysisReport);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__IsAnalysisReport(soap, &soap_tmp___Xdmrtm__IsAnalysisReport, "-Xdmrtm:IsAnalysisReport", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__IsAnalysisReport(soap, &soap_tmp___Xdmrtm__IsAnalysisReport, "-Xdmrtm:IsAnalysisReport", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__IsAnalysisReportResponse)
		return soap_closesock(soap);
	Xdmrtm__IsAnalysisReportResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__IsAnalysisReportResponse->soap_get(soap, "Xdmrtm:IsAnalysisReportResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::DeleteMonAnalysisReport(_Xdmrtm__DeleteMonAnalysisReport *Xdmrtm__DeleteMonAnalysisReport, _Xdmrtm__DeleteMonAnalysisResponse *Xdmrtm__DeleteMonAnalysisResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__DeleteMonAnalysisReport soap_tmp___Xdmrtm__DeleteMonAnalysisReport;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__DeleteMonAnalysisReport.Xdmrtm__DeleteMonAnalysisReport = Xdmrtm__DeleteMonAnalysisReport;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__DeleteMonAnalysisReport(soap, &soap_tmp___Xdmrtm__DeleteMonAnalysisReport);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__DeleteMonAnalysisReport(soap, &soap_tmp___Xdmrtm__DeleteMonAnalysisReport, "-Xdmrtm:DeleteMonAnalysisReport", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__DeleteMonAnalysisReport(soap, &soap_tmp___Xdmrtm__DeleteMonAnalysisReport, "-Xdmrtm:DeleteMonAnalysisReport", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__DeleteMonAnalysisResponse)
		return soap_closesock(soap);
	Xdmrtm__DeleteMonAnalysisResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__DeleteMonAnalysisResponse->soap_get(soap, "Xdmrtm:DeleteMonAnalysisResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int XdmrtmProxy::SubmitAlarmInfo(_Xdmrtm__SubmitAlarmInfo *Xdmrtm__SubmitAlarmInfo, _Xdmrtm__SubmitAlarmInfoResponse *Xdmrtm__SubmitAlarmInfoResponse)
{	struct soap *soap = this->soap;
	struct __Xdmrtm__SubmitAlarmInfo soap_tmp___Xdmrtm__SubmitAlarmInfo;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___Xdmrtm__SubmitAlarmInfo.Xdmrtm__SubmitAlarmInfo = Xdmrtm__SubmitAlarmInfo;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___Xdmrtm__SubmitAlarmInfo(soap, &soap_tmp___Xdmrtm__SubmitAlarmInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___Xdmrtm__SubmitAlarmInfo(soap, &soap_tmp___Xdmrtm__SubmitAlarmInfo, "-Xdmrtm:SubmitAlarmInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___Xdmrtm__SubmitAlarmInfo(soap, &soap_tmp___Xdmrtm__SubmitAlarmInfo, "-Xdmrtm:SubmitAlarmInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!Xdmrtm__SubmitAlarmInfoResponse)
		return soap_closesock(soap);
	Xdmrtm__SubmitAlarmInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	Xdmrtm__SubmitAlarmInfoResponse->soap_get(soap, "Xdmrtm:SubmitAlarmInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

} // namespace Xdmrtm

/* End of client proxy code */
