// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: touch_event.proto

#ifndef PROTOBUF_touch_5fevent_2eproto__INCLUDED
#define PROTOBUF_touch_5fevent_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace TouchEvent {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_touch_5fevent_2eproto();
void protobuf_AssignDesc_touch_5fevent_2eproto();
void protobuf_ShutdownFile_touch_5fevent_2eproto();

class Message;

enum ActionType {
  TOUCH_DOWN = 1,
  TOUCH_UP = 2,
  TOUCH_MOVE = 3
};

bool ActionType_IsValid(int value);
const ActionType ActionType_MIN = TOUCH_DOWN;
const ActionType ActionType_MAX = TOUCH_MOVE;
const int ActionType_ARRAYSIZE = ActionType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ActionType_descriptor();
inline const ::std::string& ActionType_Name(ActionType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ActionType_descriptor(), value);
}
inline bool ActionType_Parse(
    const ::std::string& name, ActionType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ActionType>(
    ActionType_descriptor(), name, value);
}
// ===================================================================

class Message : public ::google::protobuf::Message {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  void Swap(Message* other);

  // implements Message ----------------------------------------------

  Message* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .TouchEvent.ActionType actionType = 1;
  inline bool has_actiontype() const;
  inline void clear_actiontype();
  static const int kActionTypeFieldNumber = 1;
  inline ::TouchEvent::ActionType actiontype() const;
  inline void set_actiontype(::TouchEvent::ActionType value);

  // optional int32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional int32 x = 3;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 3;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // optional int32 y = 4;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 4;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);

  // optional int32 delayTime = 5;
  inline bool has_delaytime() const;
  inline void clear_delaytime();
  static const int kDelayTimeFieldNumber = 5;
  inline ::google::protobuf::int32 delaytime() const;
  inline void set_delaytime(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TouchEvent.Message)
 private:
  inline void set_has_actiontype();
  inline void clear_has_actiontype();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_delaytime();
  inline void clear_has_delaytime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  int actiontype_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  ::google::protobuf::int32 delaytime_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_touch_5fevent_2eproto();
  friend void protobuf_AssignDesc_touch_5fevent_2eproto();
  friend void protobuf_ShutdownFile_touch_5fevent_2eproto();

  void InitAsDefaultInstance();
  static Message* default_instance_;
};
// ===================================================================


// ===================================================================

// Message

// optional .TouchEvent.ActionType actionType = 1;
inline bool Message::has_actiontype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Message::set_has_actiontype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Message::clear_has_actiontype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Message::clear_actiontype() {
  actiontype_ = 1;
  clear_has_actiontype();
}
inline ::TouchEvent::ActionType Message::actiontype() const {
  return static_cast< ::TouchEvent::ActionType >(actiontype_);
}
inline void Message::set_actiontype(::TouchEvent::ActionType value) {
  assert(::TouchEvent::ActionType_IsValid(value));
  set_has_actiontype();
  actiontype_ = value;
}

// optional int32 id = 2;
inline bool Message::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Message::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Message::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Message::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Message::id() const {
  return id_;
}
inline void Message::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// optional int32 x = 3;
inline bool Message::has_x() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Message::set_has_x() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Message::clear_has_x() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Message::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Message::x() const {
  return x_;
}
inline void Message::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}

// optional int32 y = 4;
inline bool Message::has_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Message::set_has_y() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Message::clear_has_y() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Message::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Message::y() const {
  return y_;
}
inline void Message::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
}

// optional int32 delayTime = 5;
inline bool Message::has_delaytime() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Message::set_has_delaytime() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Message::clear_has_delaytime() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Message::clear_delaytime() {
  delaytime_ = 0;
  clear_has_delaytime();
}
inline ::google::protobuf::int32 Message::delaytime() const {
  return delaytime_;
}
inline void Message::set_delaytime(::google::protobuf::int32 value) {
  set_has_delaytime();
  delaytime_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace TouchEvent

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::TouchEvent::ActionType>() {
  return ::TouchEvent::ActionType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_touch_5fevent_2eproto__INCLUDED
