/* BsdrtmserviceBSDRTMSoap12Proxy.h
   Generated by gSOAP 2.8.2 from Bsdrtmservice.h
   Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef BsdrtmserviceBSDRTMSoap12Proxy_H
#define BsdrtmserviceBSDRTMSoap12Proxy_H
#include "BsdrtmserviceH.h"

namespace Bsdrtmservice {

class SOAP_CMAC BSDRTMSoap12Proxy
{ public:
	struct soap *soap;
	bool own;
	/// Endpoint URL of service 'BSDRTMSoap12Proxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	BSDRTMSoap12Proxy();
	/// Constructor to use/share an engine state
	BSDRTMSoap12Proxy(struct soap*);
	/// Constructor with endpoint URL
	BSDRTMSoap12Proxy(const char *url);
	/// Constructor with engine input+output mode control
	BSDRTMSoap12Proxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	BSDRTMSoap12Proxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	BSDRTMSoap12Proxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~BSDRTMSoap12Proxy();
	/// Initializer used by constructors
	virtual	void BSDRTMSoap12Proxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetMonStationsByUserID' (returns error code or SOAP_OK)
	virtual	int GetMonStationsByUserID(_Bsdrtmservice1__GetMonStationsByUserID *Bsdrtmservice1__GetMonStationsByUserID, _Bsdrtmservice1__GetMonStationsByUserIDResponse *Bsdrtmservice1__GetMonStationsByUserIDResponse);

	/// Web service operation 'GetMonStationsByUserID3' (returns error code or SOAP_OK)
	virtual	int GetMonStationsByUserID3(_Bsdrtmservice1__GetMonStationsByUserID3 *Bsdrtmservice1__GetMonStationsByUserID3, _Bsdrtmservice1__GetMonStationsByUserID3Response *Bsdrtmservice1__GetMonStationsByUserID3Response);

	/// Web service operation 'GetMonStationTypes' (returns error code or SOAP_OK)
	virtual	int GetMonStationTypes(_Bsdrtmservice1__GetMonStationTypes *Bsdrtmservice1__GetMonStationTypes, _Bsdrtmservice1__GetMonStationTypesResponse *Bsdrtmservice1__GetMonStationTypesResponse);

	/// Web service operation 'GetMonStationTypes3' (returns error code or SOAP_OK)
	virtual	int GetMonStationTypes3(_Bsdrtmservice1__GetMonStationTypes3 *Bsdrtmservice1__GetMonStationTypes3, _Bsdrtmservice1__GetMonStationTypes3Response *Bsdrtmservice1__GetMonStationTypes3Response);

	/// Web service operation 'GetDeviceTypes' (returns error code or SOAP_OK)
	virtual	int GetDeviceTypes(_Bsdrtmservice1__GetDeviceTypes *Bsdrtmservice1__GetDeviceTypes, _Bsdrtmservice1__GetDeviceTypesResponse *Bsdrtmservice1__GetDeviceTypesResponse);

	/// Web service operation 'GetDeviceTypes3' (returns error code or SOAP_OK)
	virtual	int GetDeviceTypes3(_Bsdrtmservice1__GetDeviceTypes3 *Bsdrtmservice1__GetDeviceTypes3, _Bsdrtmservice1__GetDeviceTypes3Response *Bsdrtmservice1__GetDeviceTypes3Response);

	/// Web service operation 'GetDevProtocols' (returns error code or SOAP_OK)
	virtual	int GetDevProtocols(_Bsdrtmservice1__GetDevProtocols *Bsdrtmservice1__GetDevProtocols, _Bsdrtmservice1__GetDevProtocolsResponse *Bsdrtmservice1__GetDevProtocolsResponse);

	/// Web service operation 'GetDevProtocols3' (returns error code or SOAP_OK)
	virtual	int GetDevProtocols3(_Bsdrtmservice1__GetDevProtocols3 *Bsdrtmservice1__GetDevProtocols3, _Bsdrtmservice1__GetDevProtocols3Response *Bsdrtmservice1__GetDevProtocols3Response);

	/// Web service operation 'GetFuncs' (returns error code or SOAP_OK)
	virtual	int GetFuncs(_Bsdrtmservice1__GetFuncs *Bsdrtmservice1__GetFuncs, _Bsdrtmservice1__GetFuncsResponse *Bsdrtmservice1__GetFuncsResponse);

	/// Web service operation 'GetFuncs3' (returns error code or SOAP_OK)
	virtual	int GetFuncs3(_Bsdrtmservice1__GetFuncs3 *Bsdrtmservice1__GetFuncs3, _Bsdrtmservice1__GetFuncs3Response *Bsdrtmservice1__GetFuncs3Response);

	/// Web service operation 'GetDevModels' (returns error code or SOAP_OK)
	virtual	int GetDevModels(_Bsdrtmservice1__GetDevModels *Bsdrtmservice1__GetDevModels, _Bsdrtmservice1__GetDevModelsResponse *Bsdrtmservice1__GetDevModelsResponse);

	/// Web service operation 'GetDevModels3' (returns error code or SOAP_OK)
	virtual	int GetDevModels3(_Bsdrtmservice1__GetDevModels3 *Bsdrtmservice1__GetDevModels3, _Bsdrtmservice1__GetDevModels3Response *Bsdrtmservice1__GetDevModels3Response);

	/// Web service operation 'GetDevModelFuncParams' (returns error code or SOAP_OK)
	virtual	int GetDevModelFuncParams(_Bsdrtmservice1__GetDevModelFuncParams *Bsdrtmservice1__GetDevModelFuncParams, _Bsdrtmservice1__GetDevModelFuncParamsResponse *Bsdrtmservice1__GetDevModelFuncParamsResponse);

	/// Web service operation 'GetDevModelFuncParams3' (returns error code or SOAP_OK)
	virtual	int GetDevModelFuncParams3(_Bsdrtmservice1__GetDevModelFuncParams3 *Bsdrtmservice1__GetDevModelFuncParams3, _Bsdrtmservice1__GetDevModelFuncParams3Response *Bsdrtmservice1__GetDevModelFuncParams3Response);

	/// Web service operation 'GetDevModelFuncParam' (returns error code or SOAP_OK)
	virtual	int GetDevModelFuncParam(_Bsdrtmservice1__GetDevModelFuncParam *Bsdrtmservice1__GetDevModelFuncParam, _Bsdrtmservice1__GetDevModelFuncParamResponse *Bsdrtmservice1__GetDevModelFuncParamResponse);

	/// Web service operation 'GetMonOrgs' (returns error code or SOAP_OK)
	virtual	int GetMonOrgs(_Bsdrtmservice1__GetMonOrgs *Bsdrtmservice1__GetMonOrgs, _Bsdrtmservice1__GetMonOrgsResponse *Bsdrtmservice1__GetMonOrgsResponse);

	/// Web service operation 'GetMonOrgs3' (returns error code or SOAP_OK)
	virtual	int GetMonOrgs3(_Bsdrtmservice1__GetMonOrgs3 *Bsdrtmservice1__GetMonOrgs3, _Bsdrtmservice1__GetMonOrgs3Response *Bsdrtmservice1__GetMonOrgs3Response);

	/// Web service operation 'GetMonControlCenters' (returns error code or SOAP_OK)
	virtual	int GetMonControlCenters(_Bsdrtmservice1__GetMonControlCenters *Bsdrtmservice1__GetMonControlCenters, _Bsdrtmservice1__GetMonControlCentersResponse *Bsdrtmservice1__GetMonControlCentersResponse);

	/// Web service operation 'GetMonControlCenters3' (returns error code or SOAP_OK)
	virtual	int GetMonControlCenters3(_Bsdrtmservice1__GetMonControlCenters3 *Bsdrtmservice1__GetMonControlCenters3, _Bsdrtmservice1__GetMonControlCenters3Response *Bsdrtmservice1__GetMonControlCenters3Response);

	/// Web service operation 'GetMonStations' (returns error code or SOAP_OK)
	virtual	int GetMonStations(_Bsdrtmservice1__GetMonStations *Bsdrtmservice1__GetMonStations, _Bsdrtmservice1__GetMonStationsResponse *Bsdrtmservice1__GetMonStationsResponse);

	/// Web service operation 'GetMonStations3' (returns error code or SOAP_OK)
	virtual	int GetMonStations3(_Bsdrtmservice1__GetMonStations3 *Bsdrtmservice1__GetMonStations3, _Bsdrtmservice1__GetMonStations3Response *Bsdrtmservice1__GetMonStations3Response);

	/// Web service operation 'GetRNCs' (returns error code or SOAP_OK)
	virtual	int GetRNCs(_Bsdrtmservice1__GetRNCs *Bsdrtmservice1__GetRNCs, _Bsdrtmservice1__GetRNCsResponse *Bsdrtmservice1__GetRNCsResponse);

	/// Web service operation 'GetRNCs3' (returns error code or SOAP_OK)
	virtual	int GetRNCs3(_Bsdrtmservice1__GetRNCs3 *Bsdrtmservice1__GetRNCs3, _Bsdrtmservice1__GetRNCs3Response *Bsdrtmservice1__GetRNCs3Response);

	/// Web service operation 'GetAllRNCs' (returns error code or SOAP_OK)
	virtual	int GetAllRNCs(_Bsdrtmservice1__GetAllRNCs *Bsdrtmservice1__GetAllRNCs, _Bsdrtmservice1__GetAllRNCsResponse *Bsdrtmservice1__GetAllRNCsResponse);

	/// Web service operation 'GetAllRNCs3' (returns error code or SOAP_OK)
	virtual	int GetAllRNCs3(_Bsdrtmservice1__GetAllRNCs3 *Bsdrtmservice1__GetAllRNCs3, _Bsdrtmservice1__GetAllRNCs3Response *Bsdrtmservice1__GetAllRNCs3Response);

	/// Web service operation 'SetRNCPassword' (returns error code or SOAP_OK)
	virtual	int SetRNCPassword(_Bsdrtmservice1__SetRNCPassword *Bsdrtmservice1__SetRNCPassword, _Bsdrtmservice1__SetRNCPasswordResponse *Bsdrtmservice1__SetRNCPasswordResponse);

	/// Web service operation 'GetDevices' (returns error code or SOAP_OK)
	virtual	int GetDevices(_Bsdrtmservice1__GetDevices *Bsdrtmservice1__GetDevices, _Bsdrtmservice1__GetDevicesResponse *Bsdrtmservice1__GetDevicesResponse);

	/// Web service operation 'GetDevices3' (returns error code or SOAP_OK)
	virtual	int GetDevices3(_Bsdrtmservice1__GetDevices3 *Bsdrtmservice1__GetDevices3, _Bsdrtmservice1__GetDevices3Response *Bsdrtmservice1__GetDevices3Response);

	/// Web service operation 'GetDevFuns' (returns error code or SOAP_OK)
	virtual	int GetDevFuns(_Bsdrtmservice1__GetDevFuns *Bsdrtmservice1__GetDevFuns, _Bsdrtmservice1__GetDevFunsResponse *Bsdrtmservice1__GetDevFunsResponse);

	/// Web service operation 'GetDevFuns3' (returns error code or SOAP_OK)
	virtual	int GetDevFuns3(_Bsdrtmservice1__GetDevFuns3 *Bsdrtmservice1__GetDevFuns3, _Bsdrtmservice1__GetDevFuns3Response *Bsdrtmservice1__GetDevFuns3Response);

	/// Web service operation 'GetDevFunAnts' (returns error code or SOAP_OK)
	virtual	int GetDevFunAnts(_Bsdrtmservice1__GetDevFunAnts *Bsdrtmservice1__GetDevFunAnts, _Bsdrtmservice1__GetDevFunAntsResponse *Bsdrtmservice1__GetDevFunAntsResponse);

	/// Web service operation 'GetDevFunAnts3' (returns error code or SOAP_OK)
	virtual	int GetDevFunAnts3(_Bsdrtmservice1__GetDevFunAnts3 *Bsdrtmservice1__GetDevFunAnts3, _Bsdrtmservice1__GetDevFunAnts3Response *Bsdrtmservice1__GetDevFunAnts3Response);

	/// Web service operation 'GetAnts3' (returns error code or SOAP_OK)
	virtual	int GetAnts3(_Bsdrtmservice1__GetAnts3 *Bsdrtmservice1__GetAnts3, _Bsdrtmservice1__GetAnts3Response *Bsdrtmservice1__GetAnts3Response);

	/// Web service operation 'GetAllAnts' (returns error code or SOAP_OK)
	virtual	int GetAllAnts(_Bsdrtmservice1__GetAllAnts *Bsdrtmservice1__GetAllAnts, _Bsdrtmservice1__GetAllAntsResponse *Bsdrtmservice1__GetAllAntsResponse);

	/// Web service operation 'AddDevUseLog' (returns error code or SOAP_OK)
	virtual	int AddDevUseLog(_Bsdrtmservice1__AddDevUseLog *Bsdrtmservice1__AddDevUseLog, _Bsdrtmservice1__AddDevUseLogResponse *Bsdrtmservice1__AddDevUseLogResponse);

	/// Web service operation 'GetMonstationUseTimeOfMonth' (returns error code or SOAP_OK)
	virtual	int GetMonstationUseTimeOfMonth(_Bsdrtmservice1__GetMonstationUseTimeOfMonth *Bsdrtmservice1__GetMonstationUseTimeOfMonth, _Bsdrtmservice1__GetMonstationUseTimeOfMonthResponse *Bsdrtmservice1__GetMonstationUseTimeOfMonthResponse);

	/// Web service operation 'GetMonstationUseTime' (returns error code or SOAP_OK)
	virtual	int GetMonstationUseTime(_Bsdrtmservice1__GetMonstationUseTime *Bsdrtmservice1__GetMonstationUseTime, _Bsdrtmservice1__GetMonstationUseTimeResponse *Bsdrtmservice1__GetMonstationUseTimeResponse);

	/// Web service operation 'GetRuningTaskIds' (returns error code or SOAP_OK)
	virtual	int GetRuningTaskIds(_Bsdrtmservice1__GetRuningTaskIds *Bsdrtmservice1__GetRuningTaskIds, _Bsdrtmservice1__GetRuningTaskIdsResponse *Bsdrtmservice1__GetRuningTaskIdsResponse);

	/// Web service operation 'GetRuningTaskById' (returns error code or SOAP_OK)
	virtual	int GetRuningTaskById(_Bsdrtmservice1__GetRuningTaskById *Bsdrtmservice1__GetRuningTaskById, _Bsdrtmservice1__GetRuningTaskByIdResponse *Bsdrtmservice1__GetRuningTaskByIdResponse);

	/// Web service operation 'AddTaskLog' (returns error code or SOAP_OK)
	virtual	int AddTaskLog(_Bsdrtmservice1__AddTaskLog *Bsdrtmservice1__AddTaskLog, _Bsdrtmservice1__AddTaskLogResponse *Bsdrtmservice1__AddTaskLogResponse);

	/// Web service operation 'SetTaskState' (returns error code or SOAP_OK)
	virtual	int SetTaskState(_Bsdrtmservice1__SetTaskState *Bsdrtmservice1__SetTaskState, _Bsdrtmservice1__SetTaskStateResponse *Bsdrtmservice1__SetTaskStateResponse);

	/// Web service operation 'AddMonAlert' (returns error code or SOAP_OK)
	virtual	int AddMonAlert(_Bsdrtmservice1__AddMonAlert *Bsdrtmservice1__AddMonAlert, _Bsdrtmservice1__AddMonAlertResponse *Bsdrtmservice1__AddMonAlertResponse);

	/// Web service operation 'GetMonAlertOfMonth' (returns error code or SOAP_OK)
	virtual	int GetMonAlertOfMonth(_Bsdrtmservice1__GetMonAlertOfMonth *Bsdrtmservice1__GetMonAlertOfMonth, _Bsdrtmservice1__GetMonAlertOfMonthResponse *Bsdrtmservice1__GetMonAlertOfMonthResponse);

	/// Web service operation 'GetMonAlertOfDay' (returns error code or SOAP_OK)
	virtual	int GetMonAlertOfDay(_Bsdrtmservice1__GetMonAlertOfDay *Bsdrtmservice1__GetMonAlertOfDay, _Bsdrtmservice1__GetMonAlertOfDayResponse *Bsdrtmservice1__GetMonAlertOfDayResponse);

	/// Web service operation 'GetPreDefinedMonitors' (returns error code or SOAP_OK)
	virtual	int GetPreDefinedMonitors(_Bsdrtmservice1__GetPreDefinedMonitors *Bsdrtmservice1__GetPreDefinedMonitors, _Bsdrtmservice1__GetPreDefinedMonitorsResponse *Bsdrtmservice1__GetPreDefinedMonitorsResponse);

	/// Web service operation 'AddMonReport' (returns error code or SOAP_OK)
	virtual	int AddMonReport(_Bsdrtmservice1__AddMonReport *Bsdrtmservice1__AddMonReport, _Bsdrtmservice1__AddMonReportResponse *Bsdrtmservice1__AddMonReportResponse);

	/// Web service operation 'DelMonReport' (returns error code or SOAP_OK)
	virtual	int DelMonReport(_Bsdrtmservice1__DelMonReport *Bsdrtmservice1__DelMonReport, _Bsdrtmservice1__DelMonReportResponse *Bsdrtmservice1__DelMonReportResponse);

	/// Web service operation 'GetMonReportOfFreq' (returns error code or SOAP_OK)
	virtual	int GetMonReportOfFreq(_Bsdrtmservice1__GetMonReportOfFreq *Bsdrtmservice1__GetMonReportOfFreq, _Bsdrtmservice1__GetMonReportOfFreqResponse *Bsdrtmservice1__GetMonReportOfFreqResponse);

	/// Web service operation 'GetMonReportsOfFreqs' (returns error code or SOAP_OK)
	virtual	int GetMonReportsOfFreqs(_Bsdrtmservice1__GetMonReportsOfFreqs *Bsdrtmservice1__GetMonReportsOfFreqs, _Bsdrtmservice1__GetMonReportsOfFreqsResponse *Bsdrtmservice1__GetMonReportsOfFreqsResponse);

	/// Web service operation 'GetMonReportFreqTypes' (returns error code or SOAP_OK)
	virtual	int GetMonReportFreqTypes(_Bsdrtmservice1__GetMonReportFreqTypes *Bsdrtmservice1__GetMonReportFreqTypes, _Bsdrtmservice1__GetMonReportFreqTypesResponse *Bsdrtmservice1__GetMonReportFreqTypesResponse);

	/// Web service operation 'ExistMonReportofFreq' (returns error code or SOAP_OK)
	virtual	int ExistMonReportofFreq(_Bsdrtmservice1__ExistMonReportofFreq *Bsdrtmservice1__ExistMonReportofFreq, _Bsdrtmservice1__ExistMonReportofFreqResponse *Bsdrtmservice1__ExistMonReportofFreqResponse);

	/// Web service operation 'GetMonReportAttachments' (returns error code or SOAP_OK)
	virtual	int GetMonReportAttachments(_Bsdrtmservice1__GetMonReportAttachments *Bsdrtmservice1__GetMonReportAttachments, _Bsdrtmservice1__GetMonReportAttachmentsResponse *Bsdrtmservice1__GetMonReportAttachmentsResponse);

	/// Web service operation 'GetMonReportAttachmentContent' (returns error code or SOAP_OK)
	virtual	int GetMonReportAttachmentContent(_Bsdrtmservice1__GetMonReportAttachmentContent *Bsdrtmservice1__GetMonReportAttachmentContent, _Bsdrtmservice1__GetMonReportAttachmentContentResponse *Bsdrtmservice1__GetMonReportAttachmentContentResponse);

	/// Web service operation 'AddMonReportAttachment' (returns error code or SOAP_OK)
	virtual	int AddMonReportAttachment(_Bsdrtmservice1__AddMonReportAttachment *Bsdrtmservice1__AddMonReportAttachment, _Bsdrtmservice1__AddMonReportAttachmentResponse *Bsdrtmservice1__AddMonReportAttachmentResponse);

	/// Web service operation 'DelMonReportAttachment' (returns error code or SOAP_OK)
	virtual	int DelMonReportAttachment(_Bsdrtmservice1__DelMonReportAttachment *Bsdrtmservice1__DelMonReportAttachment, _Bsdrtmservice1__DelMonReportAttachmentResponse *Bsdrtmservice1__DelMonReportAttachmentResponse);

	/// Web service operation 'AddMalfunctionAlert' (returns error code or SOAP_OK)
	virtual	int AddMalfunctionAlert(_Bsdrtmservice1__AddMalfunctionAlert *Bsdrtmservice1__AddMalfunctionAlert, _Bsdrtmservice1__AddMalfunctionAlertResponse *Bsdrtmservice1__AddMalfunctionAlertResponse);

	/// Web service operation 'GetMalfunctionCode' (returns error code or SOAP_OK)
	virtual	int GetMalfunctionCode(_Bsdrtmservice1__GetMalfunctionCode *Bsdrtmservice1__GetMalfunctionCode, _Bsdrtmservice1__GetMalfunctionCodeResponse *Bsdrtmservice1__GetMalfunctionCodeResponse);

	/// Web service operation 'GetAllMalfunctionAlertCount' (returns error code or SOAP_OK)
	virtual	int GetAllMalfunctionAlertCount(_Bsdrtmservice1__GetAllMalfunctionAlertCount *Bsdrtmservice1__GetAllMalfunctionAlertCount, _Bsdrtmservice1__GetAllMalfunctionAlertCountResponse *Bsdrtmservice1__GetAllMalfunctionAlertCountResponse);

	/// Web service operation 'GetPageMalfunctionAlerts' (returns error code or SOAP_OK)
	virtual	int GetPageMalfunctionAlerts(_Bsdrtmservice1__GetPageMalfunctionAlerts *Bsdrtmservice1__GetPageMalfunctionAlerts, _Bsdrtmservice1__GetPageMalfunctionAlertsResponse *Bsdrtmservice1__GetPageMalfunctionAlertsResponse);

	/// Web service operation 'GetMalfunctionAlertOfMonstationno' (returns error code or SOAP_OK)
	virtual	int GetMalfunctionAlertOfMonstationno(_Bsdrtmservice1__GetMalfunctionAlertOfMonstationno *Bsdrtmservice1__GetMalfunctionAlertOfMonstationno, _Bsdrtmservice1__GetMalfunctionAlertOfMonstationnoResponse *Bsdrtmservice1__GetMalfunctionAlertOfMonstationnoResponse);

	/// Web service operation 'SetConfirmedState' (returns error code or SOAP_OK)
	virtual	int SetConfirmedState(_Bsdrtmservice1__SetConfirmedState *Bsdrtmservice1__SetConfirmedState, _Bsdrtmservice1__SetConfirmedStateResponse *Bsdrtmservice1__SetConfirmedStateResponse);

	/// Web service operation 'GetMonStationsByVideo' (returns error code or SOAP_OK)
	virtual	int GetMonStationsByVideo(_Bsdrtmservice1__GetMonStationsByVideo *Bsdrtmservice1__GetMonStationsByVideo, _Bsdrtmservice1__GetMonStationsByVideoResponse *Bsdrtmservice1__GetMonStationsByVideoResponse);

	/// Web service operation 'GetRuningIntellTaskIds' (returns error code or SOAP_OK)
	virtual	int GetRuningIntellTaskIds(_Bsdrtmservice1__GetRuningIntellTaskIds *Bsdrtmservice1__GetRuningIntellTaskIds, _Bsdrtmservice1__GetRuningIntellTaskIdsResponse *Bsdrtmservice1__GetRuningIntellTaskIdsResponse);

	/// Web service operation 'GetIntellTask' (returns error code or SOAP_OK)
	virtual	int GetIntellTask(_Bsdrtmservice1__GetIntellTask *Bsdrtmservice1__GetIntellTask, _Bsdrtmservice1__GetIntellTaskResponse *Bsdrtmservice1__GetIntellTaskResponse);

	/// Web service operation 'AddInetllTaskLog' (returns error code or SOAP_OK)
	virtual	int AddInetllTaskLog(_Bsdrtmservice1__AddInetllTaskLog *Bsdrtmservice1__AddInetllTaskLog, _Bsdrtmservice1__AddInetllTaskLogResponse *Bsdrtmservice1__AddInetllTaskLogResponse);

	/// Web service operation 'SetInetllTaskState' (returns error code or SOAP_OK)
	virtual	int SetInetllTaskState(_Bsdrtmservice1__SetInetllTaskState *Bsdrtmservice1__SetInetllTaskState, _Bsdrtmservice1__SetInetllTaskStateResponse *Bsdrtmservice1__SetInetllTaskStateResponse);

	/// Web service operation 'GetExtendDevice' (returns error code or SOAP_OK)
	virtual	int GetExtendDevice(_Bsdrtmservice1__GetExtendDevice *Bsdrtmservice1__GetExtendDevice, _Bsdrtmservice1__GetExtendDeviceResponse *Bsdrtmservice1__GetExtendDeviceResponse);

	/// Web service operation 'GetExtendDevices' (returns error code or SOAP_OK)
	virtual	int GetExtendDevices(_Bsdrtmservice1__GetExtendDevices *Bsdrtmservice1__GetExtendDevices, _Bsdrtmservice1__GetExtendDevicesResponse *Bsdrtmservice1__GetExtendDevicesResponse);

	/// Web service operation 'GetExtendDevicesByDataTypes' (returns error code or SOAP_OK)
	virtual	int GetExtendDevicesByDataTypes(_Bsdrtmservice1__GetExtendDevicesByDataTypes *Bsdrtmservice1__GetExtendDevicesByDataTypes, _Bsdrtmservice1__GetExtendDevicesByDataTypesResponse *Bsdrtmservice1__GetExtendDevicesByDataTypesResponse);

	/// Web service operation 'GetIEMSExDevs' (returns error code or SOAP_OK)
	virtual	int GetIEMSExDevs(_Bsdrtmservice1__GetIEMSExDevs *Bsdrtmservice1__GetIEMSExDevs, _Bsdrtmservice1__GetIEMSExDevsResponse *Bsdrtmservice1__GetIEMSExDevsResponse);
};

} // namespace Bsdrtmservice

#endif
